<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{984fee79-3eda-4ea9-b09e-d08ce056b358}" SpecialFunc="None">
    <Declaration><![CDATA[
PROGRAM MAIN
VAR

END_VAR

    ]]></Declaration>
    <Implementation>
      <ST><![CDATA[POU_Example();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>